### ISSUE TITLE
License question

### ISSUE THREAD

**Issue by gorlug** [digitalpetri/ua-client-sdk#7]
The readme still says it is licensed under GNU Affero General Public License v3 but the commits/code now indicate Apache License, Version 2.0. Is this SDK now fully licensed under the Apache license?

**Comment by kevinherron** [comment]
The code in this repository is licensed under Apache, but the project is moving/has moved to the Eclipse Foundation: https://github.com/eclipse/milo

**Comment by gorlug** [comment]
Ok thanks for the info.
